### ISSUE TITLE
bug: Langfuse filter error [SSL: WRONG_VERSION_NUMBER]

### ISSUE THREAD

**Issue by timoa** [open-webui/pipelines#101]
Hello!

I've deployed Ollama, Open WebUI, Langfuse and Pipelines on a MicroK8S single node with the official Helm Charts.

I tried to use first the Langfuse filter with the corresponding ENV variables and it failed with the following error:
`httpx.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)`

Then, I redeployed pipelines with the detoxify filter and added the Langfuse filter from the Open WebUI and I got the same issue:

```bash
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9099 (Press CTRL+C to quit)
INFO:     10.1.107.152:34890 - "GET /models HTTP/1.1" 200 OK
INFO:     10.1.107.152:34898 - "GET /pipelines HTTP/1.1" 200 OK
INFO:     10.1.107.152:34908 - "GET /models HTTP/1.1" 200 OK
INFO:     10.1.107.152:34922 - "GET /detoxify_filter_pipeline/valves/spec HTTP/1.1" 200 OK
INFO:     10.1.107.152:34938 - "GET /models HTTP/1.1" 200 OK
INFO:     10.1.107.152:34940 - "GET /detoxify_filter_pipeline/valves HTTP/1.1" 200 OK
https://raw.githubusercontent.com/open-webui/pipelines/main/examples/filters/langfuse_filter_pipeline.py
on_shutdown:detoxify_filter_pipeline
Loaded module: detoxify_filter_pipeline
Loaded module: langfuse_filter_pipeline
on_startup:detoxify_filter_pipeline
on_startup:langfuse_filter_pipeline
ERROR:langfuse:[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 154, in _connect
    stream = stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 152, in start_tls
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/langfuse/client.py", line 297, in auth_check
    projects = self.client.projects.get()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langfuse/api/resources/projects/client.py", line 46, in get
    _response = self._client_wrapper.httpx_client.request(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langfuse/api/core/http_client.py", line 100, in request
    response = self.httpx_client.request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1006)
```

## Versions
| App | Image | Version |
|-----|--------|--------|
| Pipelines | ghcr.io/open-webui/pipelines:main | main (checkout 1h ago) |
| Open WebUI | ghcr.io/open-webui/open-webui:latest | v0.3.5 |
| Ollama | ollama/ollama:0.1.44 | 0.1.44 |
| Langfuse | ghcr.io/langfuse/langfuse:2.55.0 | 2.55.0 |

**Comment by timoa** [comment]
My bad. I used https instead of HTTP for the Langfuse svc.cluster.local URL 😅. It is fixed :)
