### ISSUE TITLE
Pipeline: Connection refused at VectorStoreIndex.from_documents(self.documents) 

### ISSUE THREAD

**Issue by nickibarlowSDI** [open-webui/pipelines#253]
Here is the pipeline and docker command to run it. I can get the documents to get read, but the connection is refused in attempting to create the index when I try to chat with the pipeline as a model. 
  
The embedding connection is what was refused, as demonstrated later.
I put the API key into Open WebUI, so I am able to see / use pipelines.
I specify the baseURL for the embedding.
I tried with/without specifying baseURL for base model.
My github token can read the documents on the repos, so it can't be that.

Host: Windows 10 Professional
Docker container for Open WebUI
Docker container for pipeline (with this script)

```
"""
docker build -t pipelines-unofficial . && docker run -e GITHUB_TOKEN=github_pat_... -d --name pipeline-unofficial -p 9099:9099 pipelines-unofficial
"""

from typing import List, Union, Generator, Iterator
import os
import asyncio


class Pipeline:
    def __init__(self):
        self.documents = None
        self.index = None

    async def on_startup(self):
        from llama_index.embeddings.ollama import OllamaEmbedding
        from llama_index.llms.ollama import Ollama
        from llama_index.core import VectorStoreIndex, Settings
        from llama_index.readers.github import GithubRepositoryReader, GithubClient

        Settings.embed_model = OllamaEmbedding(
            model_name="mxbai-embed-large:latest",
            base_url="http://localhost:11434",
        )
        Settings.llm = Ollama(model="ajindal/llama3.1-storm:8b")

        global index, documents

        github_token=os.environ["GITHUB_TOKEN"]
        github_token = "github_pat_..."
        owner = "..."
        repo = "..."
        branch = "main"

        try:
            github_client = GithubClient(github_token=github_token, verbose=True)
        except Exception as e:
            print(f"An error occurred setting github_client: {e}")
            self.exception = e

        try:
            reader = GithubRepositoryReader( 
                github_client=github_client,
                owner=owner,
                repo=repo,
                use_parser=False,
                verbose=False,
            )
        except Exception as e:
            print(f"An error occurred setting GithubRepositoryReader: {e}")
            self.exception = e

        try:
            loop = asyncio.new_event_loop()
        except Exception as e:
            print(f"An error occurred setting new_event_loop: {e}")
            self.exception = e

        reader._loop = loop

        try:
            # Load data from the branch
            loaded_data = reader.load_data 
            if not loaded_data:
                print("We have no loaded_data.")
                loop.close()
                return
            self.documents = await asyncio.to_thread(loaded_data, branch=branch)
            
            if not self.documents or len(self.documents) == 0:
                print("We have no documents.")
                loop.close()
                return
            else:
                print("Documents:")
                print('yes, we can print documents here')
            
            self.index = VectorStoreIndex.from_documents(self.documents)  # [Errno 111] Connection refused
        except Exception as e:
            return str(e)
        finally:
            loop.close()

        # We never get here.

    async def on_shutdown(self):
        pass

    def pipe(
        self, user_message: str, model_id: str, messages: List[dict], body: dict
    ) -> Union[str, Generator, Iterator]:
        if self.index is None:
            return "Failure: self.index is None because connection was refused."

```

**Comment by nickibarlowSDI** [comment]
Similarly, the connection is refused if I use local documents: a technique that worked on my host system.
```
        ollama_embedding = OllamaEmbedding(
            model_name=embedding_model,
        )

        Settings.embed_model = ollama_embedding 

        documents = SimpleDirectoryReader("/app/backend/data").load_data()

        # [Errno 111] Connection refused
        self.index = VectorStoreIndex.from_documents(
            documents, 
            embed_model=ollama_embedding,
            ) 
```

**Comment by nickibarlowSDI** [comment]
```
RESET_PIPELINES_DIR is not set to true. No action taken.
PIPELINES_REQUIREMENTS_PATH not specified. Skipping installation of requirements.
PIPELINES_URLS not specified. Skipping pipelines download and installation.
INFO:     Started server process [7]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 245, in lifespan
    await on_startup()
  File "/app/main.py", line 224, in on_startup
    await module.on_startup()
  File "/app/./pipelines/pipeline-simple-rag.py", line 46, in on_startup
    self.index = await VectorStoreIndex.from_documents(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 119, in from_documents
    return cls(
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 75, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 77, in __init__
    index_struct = self.build_index_from_nodes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 307, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **insert_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 278, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 231, in _add_nodes_to_index
    nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/indices/vector_store/base.py", line 138, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
                      ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/indices/utils.py", line 138, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 265, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/base/embeddings/base.py", line 335, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/embeddings/ollama/base.py", line 75, in _get_text_embeddings
    embeddings = self.get_general_text_embedding(text)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/embeddings/ollama/base.py", line 88, in get_general_text_embedding
    result = self._client.embeddings(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ollama/_client.py", line 281, in embeddings
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ollama/_client.py", line 70, in _request
    response = self._client.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 837, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 235, in handle_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 111] Connection refused
```

**Comment by nickibarlowSDI** [comment]
Apparently it's http://localhost:11434/api/embeddings causing the issues.

**Comment by nickibarlowSDI** [comment]
This has the same effect.
`
        for i, d in enumerate(documents):
            # response = ollama.embeddings(model="mxbai-embed-large", prompt="hi")
            # response = ollama.embeddings(model="mxbai-embed-large:latest", prompt="hi")
            # response = ollama.embeddings(model="local:mxbai-embed-large:latest", prompt="hi")
            response = ollama.embeddings(model="nomic-embed-text", prompt="hi")`

**Comment by nickibarlowSDI** [comment]
Solution: set the embedding base_url to base_url="http://host.docker.internal:11434"
