### ISSUE TITLE
Error when installing from script

### ISSUE THREAD

**Issue by CraftzAdmin** [open-webui/pipelines#365]
Hello everyone,
Just want to report, receiving this error when installing from the docker installer:

`dockerrun -d -p 9099:9099 --add-host=host.docker.internal:host-gateway -v pipelines:/app/pipelines --name pipelines --restart always ghcr.io/open-webui/pipelines:main` 

2024-12-12T14:49:02.009401263Z ERROR:    Traceback (most recent call last):
2024-12-12T14:49:02.009441299Z   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
2024-12-12T14:49:02.009450897Z     async with self.lifespan_context(app) as maybe_state:
2024-12-12T14:49:02.009477042Z   File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
2024-12-12T14:49:02.009485999Z     return await anext(self.gen)
2024-12-12T14:49:02.009493763Z            ^^^^^^^^^^^^^^^^^^^^^
2024-12-12T14:49:02.009501096Z   File "/app/main.py", line 248, in lifespan
2024-12-12T14:49:02.009508693Z     await on_startup()
2024-12-12T14:49:02.009516062Z   File "/app/main.py", line 227, in on_startup
2024-12-12T14:49:02.009523566Z     await module.on_startup()
2024-12-12T14:49:02.009530959Z   File "/app/./pipelines/llamaindex_pipeline.py", line 28, in on_startup
2024-12-12T14:49:02.009538643Z     self.documents = SimpleDirectoryReader("./data").load_data()
2024-12-12T14:49:02.009546527Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-12T14:49:02.009554157Z   File "/usr/local/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 260, in __init__
2024-12-12T14:49:02.009561958Z     raise ValueError(f"Directory {input_dir} does not exist.")
2024-12-12T14:49:02.009569799Z ValueError: Directory ./data does not exist.
2024-12-12T14:49:02.009577222Z 
2024-12-12T14:49:02.009584408Z ERROR:    Application startup failed. Exiting.
2024-12-12T14:49:02.009921438Z Installing requirement: llama-index
2024-12-12T14:49:02.009947884Z Loaded module: llamaindex_pipeline
2024-12-12T14:49:02.009956596Z Installing requirement: requests
2024-12-12T14:49:02.009964791Z Installing requirement: sseclient-py
2024-12-12T14:49:02.009972582Z Loaded module: anthropic_manifold_pipeline
2024-12-12T14:49:02.009980052Z Loaded module: wikipedia_pipeline
2024-12-12T14:49:02.009987556Z Installing requirement: detoxify
2024-12-12T14:49:02.009994942Z Loaded module: detoxify_filter_pipeline
2024-12-12T14:49:03.368862279Z RESET_PIPELINES_DIR is not set to true. No action taken.
2024-12-12T14:49:03.368906641Z PIPELINES_REQUIREMENTS_PATH not specified. Skipping installation of requirements.
2024-12-12T14:49:03.369272811Z PIPELINES_URLS not specified. Skipping pipelines download and installation.
2024-12-12T14:49:04.226470082Z INFO:     Started server process [7]
2024-12-12T14:49:04.226527079Z INFO:     Waiting for application startup.

I've updated the PIP, tried to install again, it runs for the first time, then when trying to pull a model from github, it trows an error: 
![2024-12-12_05h19_15](https://github.com/user-attachments/assets/f03dfec2-2f23-45ba-a8b0-8b20bf7f47fd)

**Comment by CraftzAdmin** [comment]
Hi all, to give an update: in my case, it's working now:

Steps: 
1)Removed the container
2) Recreated the container using the default
3) Using Portainer, accessed the Console, updated pip
4) Run a pip install on the requirements.txt again
5) Connected to openwebUI using the INTERNAL IP from docker, in my case 172.17.0.4, **instead of** localhost or host.docker.internal

6) The issue with the /.data was caused because I used a URL with SSL, set up with Let's Encrypt and Nginx. therefore, the logs showed an error after pulling the pipeline from GitHub as **"POST /pipelines/add HTTP/1.1" 500 Internal Server Error**

7) Switched to the non SSL version, and performed the same action, working now. I believe if everything is ok. 

Thanks!
